import { describe, expect, it } from 'vitest';
import { RULESET_V1, SUFFIX } from '@vert/engine';
import type { ReadinessOutcome, ReadinessTestConfig, ReadinessTestSession } from '@vert/engine';
import { buildEngineFixture } from '../../data/fixtures/fromEngine';
import type { SessionExercise } from '../../data/types';
import { RNT_CAPTION, climbPrescription } from './climbRows';
import { fingerPainNotice, hasHardFingerWork } from './climbing';
import { buildTodaySession, flattenExercises, type TodayExercise } from './model';
import { readinessRowModel, whoopChannel } from './readinessModel';
import { nextUpLabel } from './rest';
import { rowDetail } from './rows';

/**
 * The climbing owner's week 7, through the runner's own merge.
 *
 * The fixture is generated by the engine, so these are the rows the athlete
 * actually sees on Monday, Tuesday and Thursday: a weighted pull-up in added
 * load, throws counted in repetitions, the knee-alignment row with what ends
 * its set, and the two questions the day is allowed to ask.
 */

const fixture = buildEngineFixture('2026-10-22', 'UTC');
const CONFIG: ReadinessTestConfig = { ...RULESET_V1.constants.climbing.readiness };
const MONDAY = 'w7-d0';
const TUESDAY = 'w7-d1';
const THURSDAY = 'w7-d2';

function rowsFor(sessionKey: string): SessionExercise[] {
  const session = fixture.sessions.find((entry) => entry.key === sessionKey);
  if (session === undefined) throw new Error(`no fixture session ${sessionKey}`);
  return session.exercises.map((exercise) => ({
    id: exercise.key,
    sessionId: session.key,
    orderIndex: exercise.orderIndex,
    exerciseId: exercise.exerciseId,
    exerciseName: exercise.exerciseName,
    block: exercise.block ?? null,
    loadType: exercise.loadType,
    loadMode: exercise.loadMode ?? 'entered',
    bothSides: exercise.bothSides ?? false,
    rotationNote: exercise.rotationNote ?? null,
    headerNote: exercise.headerNote ?? null,
    lastTimeNote: exercise.lastTimeNote ?? null,
    isNewThisWeek: exercise.isNewThisWeek ?? false,
    restS: exercise.restS ?? null,
    restRule: exercise.restRule ?? null,
    perSet: exercise.perSet,
  }));
}

function snapshotFor(sessionKey: string): unknown {
  return fixture.sessions.find((entry) => entry.key === sessionKey)?.snapshot;
}

function find(session: ReturnType<typeof buildTodaySession>, id: string): TodayExercise | undefined {
  return flattenExercises(session).find((entry) => entry.exerciseId === id);
}

/** Nine steady throws behind the gate, so the median is trusted. */
const HISTORY: ReadinessTestSession[] = [7.0, 7.2, 7.1, 7.0, 7.2, 7.1, 7.1, 7.2, 7.0].map(
  (best, index) => ({
    id: `throw-${index}`,
    date: `2026-10-${String(index + 1).padStart(2, '0')}`,
    kind: 'seated_mb_throw',
    attempts: [best],
    best,
    unit: 'm',
  }),
);

function outcomeFor(score: number | null, best: number): ReadinessOutcome {
  const model = readinessRowModel({
    config: CONFIG,
    whoop: whoopChannel({ date: '2026-10-22', score }),
    test: { id: 'today', date: '2026-10-22', kind: 'seated_mb_throw', attempts: [best], best, unit: 'm' },
    history: HISTORY,
  });
  if (model.outcome === null) throw new Error('the gate had nothing to read');
  return model.outcome;
}

describe('week 7 Tuesday, the upper power day', () => {
  const session = buildTodaySession(rowsFor(TUESDAY), snapshotFor(TUESDAY), { medBallLb: 6 });

  it('shows the weighted pull-up in added load and nothing else', () => {
    const pullUp = find(session, 'weighted_pull_up');
    expect(pullUp).toBeDefined();
    if (pullUp === undefined) return;
    expect(pullUp.sets.length).toBeGreaterThan(0);
    for (const set of pullUp.sets) {
      expect(set.displayLoad).toMatch(/^\d+ × BW \+ \d+ lb$/u);
      // Never rebuilt here: it is the engine's own notation on the row.
      expect(climbPrescription(set, pullUp.repCounted)).toBe(set.displayLoad);
    }
    expect(pullUp.sets[0]?.displayLoad.startsWith('5 × BW + ')).toBe(true);
  });

  it('says what the hands do on every pulling row', () => {
    const pullUp = find(session, 'weighted_pull_up');
    expect(pullUp?.captions).toContain('Open hand only');
  });

  it('counts the overspeed pull in repetitions, with the open-hand cue', () => {
    const pull = find(session, 'band_assisted_overspeed_pull');
    expect(pull).toBeDefined();
    if (pull === undefined) return;
    expect(pull.repCounted).toBe(true);
    expect(climbPrescription(pull.sets[0] as never, true)).toBe('3 reps');
    expect(pull.captions).toContain('Open hand only');
  });

  it('counts the throws in repetitions and names the ball on the second line', () => {
    const chest = find(session, 'med_ball_chest_throw');
    expect(chest).toBeDefined();
    if (chest === undefined) return;
    expect(chest.repCounted).toBe(true);
    expect(chest.rowNote).toBe('6 lb ball');
    const first = chest.sets[0];
    expect(first).toBeDefined();
    if (first === undefined) return;
    expect(climbPrescription(first, chest.repCounted)).toBe('3 reps');
    expect(rowDetail({ set: first, bothSides: chest.bothSides, note: chest.rowNote })).toContain(
      '6 lb ball',
    );
  });

  it('says nothing about the ball when the inventory names no weight', () => {
    const plain = buildTodaySession(rowsFor(TUESDAY), snapshotFor(TUESDAY));
    expect(find(plain, 'med_ball_chest_throw')?.rowNote).toBeNull();
  });

  it('says what ends the knee-alignment set, and which leg goes first', () => {
    const rnt = find(session, 'rnt_split_squat');
    expect(rnt?.captions).toEqual(['Weaker side first: left', RNT_CAPTION]);
  });

  it('names the weaker side on every unilateral row the engine ordered', () => {
    const rotational = find(session, 'med_ball_rotational_throw');
    expect(rotational?.captions).toContain('Weaker side first: left');
  });
});

describe('the finger question', () => {
  it('is asked on the day that carries hard finger work', () => {
    expect(hasHardFingerWork(rowsFor(TUESDAY))).toBe(true);
  });

  it('is not asked on a day that carries none', () => {
    expect(hasHardFingerWork(rowsFor(THURSDAY))).toBe(false);
    expect(hasHardFingerWork(rowsFor(MONDAY))).toBe(false);
  });

  it('leaves the day alone at the ceiling', () => {
    const session = buildTodaySession(rowsFor(TUESDAY), snapshotFor(TUESDAY), {
      fingerPain: 3,
      fingerPainCeiling: 3,
    });
    expect(find(session, 'weighted_pull_up')).toBeDefined();
    expect(session.notices.join(' ')).not.toContain('Finger pain');
  });

  it('takes every hard finger row out one point over it, and says so', () => {
    const session = buildTodaySession(rowsFor(TUESDAY), snapshotFor(TUESDAY), {
      fingerPain: 4,
      fingerPainCeiling: 3,
    });
    expect(find(session, 'weighted_pull_up')).toBeUndefined();
    expect(find(session, 'band_assisted_overspeed_pull')).toBeUndefined();
    expect(find(session, 'hangboard_open_hand_hang')).toBeUndefined();
    // The throws and the press are not finger work, so they stay.
    expect(find(session, 'med_ball_chest_throw')).toBeDefined();
    expect(find(session, 'db_press')).toBeDefined();
    expect(session.notices).toContain(fingerPainNotice(4, 3));
  });

  it('names the answer and the ceiling in the notice', () => {
    expect(fingerPainNotice(5, 3)).toBe(
      'Finger pain at 5 out of 10, over your ceiling of 3: the hard finger work is out of ' +
        "today's session.",
    );
  });

  it('is not the exercise-cap line: a removed row is explained by its own notice', () => {
    const session = buildTodaySession(rowsFor(TUESDAY), snapshotFor(TUESDAY), {
      fingerPain: 6,
      fingerPainCeiling: 3,
    });
    expect(session.trimmed.map((entry) => entry.name)).not.toContain('Weighted pull-up');
  });

  it('puts the rows back when the answer comes down', () => {
    const back = buildTodaySession(rowsFor(TUESDAY), snapshotFor(TUESDAY), {
      fingerPain: 1,
      fingerPainCeiling: 3,
    });
    expect(find(back, 'weighted_pull_up')).toBeDefined();
    expect(back.notices.join(' ')).not.toContain('Finger pain');
  });
});

describe('the readiness gate on the test day', () => {
  const plain = buildTodaySession(rowsFor(THURSDAY), snapshotFor(THURSDAY));
  const low = outcomeFor(31, 6.2);
  const cut = buildTodaySession(rowsFor(THURSDAY), snapshotFor(THURSDAY), { readiness: low });

  it('drops the day one tier, in the header and in a notice', () => {
    expect(low.state).toBe('both_low');
    expect(cut.headerSuffixes).toContain(SUFFIX.readinessTierDown);
    expect(cut.notices).toContain(low.line);
  });

  it('takes the maximal jumps out and cuts what is left', () => {
    const before = flattenExercises(plain).length;
    expect(flattenExercises(cut).length).toBeLessThan(before);
    const pogo = find(cut, 'pogo_hops');
    const pogoBefore = find(plain, 'pogo_hops');
    expect(pogo).toBeDefined();
    expect(pogoBefore).toBeDefined();
    if (pogo === undefined || pogoBefore === undefined) return;
    expect(pogo.sets[0]?.reps).toBeLessThan(pogoBefore.sets[0]?.reps ?? 0);
    // Reversible on screen: every reduced row keeps its unreduced twin.
    expect(pogo.sets[0]?.original?.reps).toBe(pogoBefore.sets[0]?.reps);
  });

  it('never raises anything', () => {
    for (const exercise of flattenExercises(cut)) {
      const before = find(plain, exercise.exerciseId);
      if (before === undefined) continue;
      exercise.sets.forEach((set, index) => {
        const original = before.sets[index];
        if (original?.reps === undefined || set.reps === undefined) return;
        expect(set.reps).toBeLessThanOrEqual(original.reps + 2);
      });
    }
  });

  it('undoes itself when the entry changes, rather than cutting twice', () => {
    const high = outcomeFor(73, 7.15);
    const back = buildTodaySession(rowsFor(THURSDAY), snapshotFor(THURSDAY), { readiness: high });
    expect(high.state).toBe('both_high');
    expect(back.headerSuffixes).not.toContain(SUFFIX.readinessTierDown);
    expect(flattenExercises(back).length).toBe(flattenExercises(plain).length);
    const pogo = find(back, 'pogo_hops');
    expect(pogo?.sets[0]?.reps).toBe(find(plain, 'pogo_hops')?.sets[0]?.reps);
    expect(pogo?.sets[0]?.original).toBeUndefined();
    expect(back.notices).not.toContain(low.line);
  });

  it('carries only one gate line, never the one the week was built with beside it', () => {
    const lines = cut.notices.filter((line) => line.startsWith('Readiness:'));
    expect(lines).toEqual([low.line]);
  });
});

describe('the rest bar, after the first primer set', () => {
  const monday = buildTodaySession(rowsFor(MONDAY), snapshotFor(MONDAY));
  const exercises = flattenExercises(monday);

  it('names the next counted set, not an unticked warm-up row', () => {
    const pogo = exercises.find((entry) => entry.exerciseId === 'pogo_hops');
    expect(pogo).toBeDefined();
    if (pogo === undefined) return;
    const first = pogo.sets[0];
    if (first === undefined) return;

    const label = nextUpLabel({
      exercises,
      isLogged: (id, setNumber) => id === pogo.id && setNumber === first.setNumber,
      from: { exerciseId: pogo.id, set: first },
    });
    expect(label).toBe('next: set 2 · 5 × BW');
    expect(label).not.toContain('Banded lateral walk');
  });

  it('crosses to the next counted exercise once the primer is done', () => {
    const pogo = exercises.find((entry) => entry.exerciseId === 'pogo_hops');
    if (pogo === undefined) return;
    const label = nextUpLabel({
      exercises,
      isLogged: (id) => id === pogo.id,
      from: null,
    });
    expect(label).toContain('Box squat');
    expect(label).not.toContain('walk');
  });
});
