// generated by scripts/gen-tokens.mjs, do not edit
// Source of truth: apps/mobile/src/ui/tokens.oklch.ts
// Regenerate with: npm run tokens

export type SchemeName = 'light' | 'dark';

export type DataTokenName =
  | 'category.strength'
  | 'category.plyometrics'
  | 'category.technique'
  | 'category.mobility'
  | 'recovery.low'
  | 'recovery.moderate'
  | 'recovery.high';

export interface SchemeColors {
  /** The ground. Never pure white, never pure black. */
  readonly paper: string;
  /** A second neutral for panels, the bottom bar, and inputs. */
  readonly paper2: string;
  /** A third neutral for pressed states. */
  readonly paper3: string;
  /** Primary text and hairlines. */
  readonly ink: string;
  /** Secondary text. */
  readonly ink2: string;
  /** Tertiary text, still at or above 4.5:1 on paper and paper2. */
  readonly ink3: string;
  /** The single accent. */
  readonly green: string;
  /** A quiet green ground for the selected row. */
  readonly greenSoft: string;
  /** Text on a committed green surface. */
  readonly onGreen: string;
  /** 1px hairline. */
  readonly rule: string;
  /** A heavier rule for chart axes. */
  readonly ruleStrong: string;
  /** Charts, chips, and glyph fills only. Never chrome, never text. */
  readonly data: Readonly<Record<DataTokenName, string>>;
}

export const colors: Readonly<Record<SchemeName, SchemeColors>> = {
  light: {
    paper: '#f0f5f2',
    paper2: '#e5ece7',
    paper3: '#dae2dc',
    ink: '#161d18',
    ink2: '#4f5851',
    ink3: '#636b65',
    green: '#005e2f',
    greenSoft: '#c8e7d1',
    onGreen: '#eff8f2',
    rule: 'rgba(22, 29, 24, 0.16)',
    ruleStrong: 'rgba(22, 29, 24, 0.42)',
    data: {
      'category.strength': '#2a78d6',
      'category.plyometrics': '#d9662e',
      'category.technique': '#4a3aa7',
      'category.mobility': '#d4638f',
      'recovery.low': '#c9302d',
      'recovery.moderate': '#cf9c00',
      'recovery.high': '#009342',
    },
  },
  dark: {
    paper: '#171411',
    paper2: '#211d1a',
    paper3: '#2c2824',
    ink: '#e9e4dc',
    ink2: '#a9a49c',
    ink3: '#8d8982',
    green: '#60bb83',
    greenSoft: '#173523',
    onGreen: '#040c06',
    rule: 'rgba(233, 228, 220, 0.16)',
    ruleStrong: 'rgba(233, 228, 220, 0.4)',
    data: {
      'category.strength': '#3987e5',
      'category.plyometrics': '#d95926',
      'category.technique': '#9085e9',
      'category.mobility': '#d55181',
      'recovery.low': '#e0574c',
      'recovery.moderate': '#c98500',
      'recovery.high': '#27a05b',
    },
  },
};
