/** The Whoop feature's public surface. */
export { WhoopScreen } from './whoopScreen';
export {
  createFixtureClient,
  createServerClient,
  createWhoopClient,
  readStatus,
  readSync,
  serverUrl,
  WhoopClientError,
  WHOOP_APP_REDIRECT,
  type FixtureWhoopState,
  type WhoopClient,
  type WhoopConnectOutcome,
  type WhoopConnectResult,
  type WhoopStartResponse,
  type WhoopErrorKind,
  type WhoopStatus,
  type WhoopStatusResponse,
  type WhoopSyncResponse,
} from './client';
export {
  AUTOREGULATION_PAUSED_LINE,
  DATA_BY_WHOOP,
  connectedLine,
  cooldownRemainingMs,
  errorLine,
  gateCriterionLine,
  headlineFor,
  importingLine,
  NO_SERVER_ACTION_CAPTION,
  NO_SERVER_LINE,
  syncLabel,
  SYNC_COOLDOWN_MS,
} from './copy';
export {
  HINT_SESSIONS,
  SPORT_ALLOWLIST,
  STRENGTH_TRAINER_HINT,
  WINDOW_PAD_MS,
  matchWindow,
  matchWorkout,
  overlapSeconds,
  rankCandidates,
  showsStrengthTrainerHint,
  sportRank,
  type MatchCandidate,
  type MatchSession,
  type MatchWorkout,
} from './match';
export {
  BASELINE_DAYS,
  RULEBOOK_ALWAYS_ON,
  bandFor,
  bandWord,
  describeModifier,
  evaluateShadow,
  modifierFor,
  shadowLine,
  type ShadowBand,
  type ShadowEvaluation,
  type ShadowModifier,
} from './shadow';
export { buildGateInput, evaluateGate, weekKey, type GateSource } from './gateInputs';
